---
title: "An interactive report with Shiny"
author: "UPSC Tech Seminar"
output:
  html_document:
    code_folding: hide
runtime: shiny
date: "2024-05-29"
---

## R Markdown

You can write your report and embed code output as in any Markdown document.

```{r}
summary(iris$Sepal.Length)
```

## Including an interactive Shiny app

Now comes the Shiny app:

```{r}
### Modified from RaukR 2023 Shiny lab

library(shiny)
library(ggplot2)

shinyApp(
  ui = fluidPage(
    titlePanel("Data explorer"),
    sidebarLayout(
      sidebarPanel(
        selectInput("in_x", "X axis variable", choices = colnames(iris), selected = colnames(iris)[1]),
        selectInput("in_y", "Y axis variable", choices = colnames(iris), selected = colnames(iris)[2]),
        selectInput("in_col", "Colour variable", choices = colnames(iris), selected = colnames(iris)[5]),
        downloadButton("downloadPlot", "Download Plot")
      ),
      mainPanel(
        plotOutput("out_plot")
      )
    )
  ),
  server = function(input, output) {
    gg <- reactive({
      ggplot(iris, aes(x = !!sym(input$in_x), y = !!sym(input$in_y), col = !!sym(input$in_col))) +
        geom_point()
    })
    
    output$out_plot <- renderPlot({
      gg()
    })
    
    output$downloadPlot <- downloadHandler(
      filename = function() {
        paste("plot", Sys.time(), ".png", sep = "")
      },
      content = function(file) {
        ggsave(file, gg())
      }
    )
  },
  options = list(height = 1000)
)
```
